name: test

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'web/**'

jobs:
  web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: ./web
        run: npm install
        shell: bash

      - name: Run formatter
        working-directory: ./web
        run: npm run format
        shell: bash

      - name: Check for uncommitted changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            git diff
            exit 1
          fi

      - name: Build the app
        working-directory: ./web
        run: npm run build
        shell: bash
